safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Sebastian Ankargren"
description: "Ph. D. Student<br>Department of Statistics<br>Uppsala University"
baseurl: ""
url: "https://ankargren.github.io/" # replace by your site's url
twitter_username: 
github_username:  ankargren # (your name)
orcid_username: 0000-0003-4415-8734
linkedin_username: sebastianankargren
accent: "#ffffff" # accent color for blog column
picture: linkedin.jpg


author: "Sebastian Ankargren"
address: "Department of Statistics<br>Box 513<br>751 48 Uppsala<br>Sweden"
email: "sebastian.ankargren@statistics.uu.se"
cv: CV_Sebastian_Ankargren.pdf

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md

